### PR TITLE
Move locales-en-US.xml from wasm crate to csl

### LINKED ISSUE #23: Cannot build citeproc-db with `cargo vendor`
@doronbehar and I maintain [texlab for the Nix package manager](https://github.com/NixOS/nixpkgs/blob/f3402a38dacb56f3c6145bb8cabd087efa3e5e90/pkgs/development/tools/misc/texlab/default.nix) and I've encountered the following error trying to build 1.8.0 (which now uses citeproc-rs):

```
error: couldn't read /tmp/nix/texlab/texlab-1.8.0-vendor/citeproc-db/src/../../wasm/src/locales-en-US.xml: No such file or directory (o
s error 2)                                                                                                                            
   --> /tmp/nix/texlab/texlab-1.8.0-vendor/citeproc-db/src/xml.rs:320:13
    |
320 |             include_str!("../../wasm/src/locales-en-US.xml").to_string(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```
This seems to be an issue with `citeproc-db` depending on `locales-en-US.xml` in `citeproc-wasm`.  

For a normal run of `cargo build` this isn't an issue, but if the dependencies are vendored prior to running `cargo build`, `citeproc-db` will be compiled independently from `citeproc-wasm`, and it won't find `locales-en-US.xml`.

This can be reproduced by:
- Setting the working directory to the texlab repo
- Running `cargo vendor`
- Following the instructions displayed in the output, for example:
```
To use vendored sources, add this to your .cargo/config for this project:

[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/cormacrelf/citeproc-rs"]
git = "https://github.com/cormacrelf/citeproc-rs"
rev = "796ea0382392ae1befdc39f21162ed83b640ac29"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/tmp/texlab/vendor"
```
- Running `cargo build`

### PR DESCRIPTION
**Pull request by MetaDark**
Currently the `db` crate can't be built in isolation since it depends on
on `locales-en-US.xml`, which exists outside of the crate.

This commit moves `locales-en-US.xml` to `csl`, and exposes the contents
of the file through `EN_US` so it can be used from other crates.

Fixes #23
--

This fixes the problem, but please let me know if you can think of a better way of approaching this.

### CODE REVIEW

**Comment by MetaDark** [comment]
@doronbehar

**Comment by cormacrelf** [comment]
LGTM, thanks for driving this one.

**Comment by dstillman** [comment]
(Presumably we eventually want to just use a submodule of the the CSL locales repo, though, right?)

**Comment by cormacrelf** [comment]
Submodules are annoying enough to update; `locales-en-US.xml` changes once every few years and it's a big event when it does (only when there's a feature addition to the spec); the rest of the locales are not needed to build the program.

When I say "build the program" I mean for tests and for the wasm code to avoid a constant 1 extra HTTP request that blocks using the processor. The rest of the time, it is expected that locales will be present in the end-user's filesystem or available over CDN/HTTP. But I don't care if a few kB makes it into an overall pretty large native binary, so this is fine.

**Comment by dstillman** [comment]
Ah, OK, I didn't realize the other locales wouldn't be needed eventually.

**Pull request merged**
